### ISSUE TITLE
想问下开启失败是为什么。

### ISSUE THREAD

**Issue by RainbowDashKira** [YuuzukiRin/nonebot_plugin_impart#1]
Running Matcher(type='message', module=nonebot_plugin_impart, lineno=74) failed.
Traceback (most recent call last):
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 147, in execute
    self._adapt_connection._handle_exception(error)
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 298, in _handle_exception
    raise error
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 129, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "E:\BOT\rainbow\.venv\lib\site-packages\aiosqlite\cursor.py", line 48, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "E:\BOT\rainbow\.venv\lib\site-packages\aiosqlite\cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "E:\BOT\rainbow\.venv\lib\site-packages\aiosqlite\core.py", line 132, in _execute
    return await future
  File "E:\BOT\rainbow\.venv\lib\site-packages\aiosqlite\core.py", line 115, in run
    result = function()
sqlite3.OperationalError: no such table: groupdata

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "E:\BOT\rainbow\.venv\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "E:\BOT\rainbow\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot_plugin_impart\handle.py", line 553, in open_module
    await set_group_allow(gid, True)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot_plugin_impart\data_sheet.py", line 148, in set_group_allow
    if not await check_group_allow(groupid):
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot_plugin_impart\data_sheet.py", line 141, in check_group_allow
    result = await s.execute(select(GroupData.allow).filter(GroupData.groupid == groupid))
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 461, in execute
    result = await greenlet_spawn(
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 2362, in execute
    return self._execute_internal(
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\orm\context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 147, in execute
    self._adapt_connection._handle_exception(error)
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 298, in _handle_exception
    raise error
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 129, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "E:\BOT\rainbow\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "E:\BOT\rainbow\.venv\lib\site-packages\aiosqlite\cursor.py", line 48, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "E:\BOT\rainbow\.venv\lib\site-packages\aiosqlite\cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "E:\BOT\rainbow\.venv\lib\site-packages\aiosqlite\core.py", line 132, in _execute
    return await future
  File "E:\BOT\rainbow\.venv\lib\site-packages\aiosqlite\core.py", line 115, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: groupdata
[SQL: SELECT groupdata.allow
FROM groupdata
WHERE groupdata.groupid = ?]
[parameters: (326571422,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by YuuzukiRin** [comment]
已修复

**Comment by RainbowDashKira** [comment]
帮助会报错
Running Matcher(type='message', module=nonebot_plugin_impart, lineno=94) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "E:\BOT\rainbow\.venv\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "E:\BOT\rainbow\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot_plugin_impart\handle.py", line 602, in yinpa_introduce
    usage_text = plugin_config.plugin_usage()
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot_plugin_impart\config.py", line 124, in plugin_usage
    return Config().usage
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Config
nickname
  field required (type=value_error.missing)

**Comment by YuuzukiRin** [comment]
已修复
